runtime: python27
api_version: 1
threadsafe: true
service: api-docs

handlers:
- url: /?$
  static_files: index.html
  upload: index\.html
  login: admin
  secure: always

- url: /openapi\.yaml
  static_files: openapi.yaml
  upload: openapi\.yaml
  login: admin
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?\..*$
- ^node_modules/
