runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/v1/.*
  script: app.api.wsgi.app
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*$
- ^node_modules/
- ^tests/
