runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/v1/.*
  script: app.api.wsgi.app
  secure: always

- url: /api-docs/?$
  static_files: api-docs/index.html
  upload: api-docs/index\.html
  login: admin
  secure: always

- url: /api-docs/openapi\.yaml
  static_files: api-docs/openapi.yaml
  upload: api-docs/openapi\.yaml
  login: admin
  secure: always
  application_readable: true

libraries:
- name: ujson
  version: '1.35'

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*$
- ^node_modules/
- ^tests/
