runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/v1/.*
  script: app.api.wsgi.app
  secure: always

libraries:
- name: yaml
  version: '3.10'

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*$
- ^node_modules/(?!api-docs).*$
- ^node_modules/api-docs/(?!openapi\.yaml).*$
- ^tests/
